using Content.Shared._Impstation.Thaven;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.Thaven.Eui;

[GenerateTypedNameReferences]
public sealed partial class NewThavenMoodWindow : DefaultWindow
{
    public event Action<ThavenMood>? MoodSaved;

    public NewThavenMoodWindow()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Close();
        SaveButton.OnPressed += _ =>
        {
            var title = MoodTitle.Text.Trim();
            var description = Rope.Collapse(MoodDescription.TextRope).Trim();

            if (string.IsNullOrWhiteSpace(title) || string.IsNullOrWhiteSpace(description))
                return;

            MoodSaved?.Invoke(new ThavenMood
            {
                MoodName = title,
                MoodDesc = description,
            });

            Close();
        };
    }
}
