using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Thaven;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.Thaven.Eui;

[GenerateTypedNameReferences]
public sealed partial class ThavenMoodUi : FancyWindow
{
    private List<ThavenMood> _moods = new();
    private List<ThavenMood> _sharedMoods = new();
    private NewThavenMoodWindow? _newMoodWindow;

    public ThavenMoodUi()
    {
        RobustXamlLoader.Load(this);
        NewMoodButton.OnPressed += _ => AddNewMood(false);
        NewSharedMoodButton.OnPressed += _ => AddNewMood(true);
    }

    private void AddNewMood(bool shared)
    {
        if (_newMoodWindow != null)
            return;

        _newMoodWindow = new NewThavenMoodWindow();
        _newMoodWindow.MoodSaved += mood =>
        {
            if (shared)
            {
                var updatedSharedMoods = GetSharedMoods();
                updatedSharedMoods.Add(mood);
                SetState(GetMoods(), updatedSharedMoods);
            }
            else
            {
                var updatedMoods = GetMoods();
                updatedMoods.Add(mood);
                SetState(updatedMoods, GetSharedMoods());
            }
        };
        _newMoodWindow.OnClose += () => _newMoodWindow = null;
        _newMoodWindow.OpenCentered();
    }

    private static List<ThavenMood> ReadMoods(BoxContainer container)
    {
        var newMoods = new List<ThavenMood>();

        foreach (var control in container.Children)
        {
            if (control is not MoodContainer moodControl)
                continue;

            if (string.IsNullOrWhiteSpace(moodControl.ThavenMoodTitle.Text))
                continue;

            var moodText = Rope.Collapse(moodControl.ThavenMoodContent.TextRope).Trim();

            if (string.IsNullOrWhiteSpace(moodText))
                continue;

            var mood = new ThavenMood()
            {
                MoodName = moodControl.ThavenMoodTitle.Text,
                MoodDesc = moodText,
            };

            newMoods.Add(mood);
        }

        return newMoods;
    }

    public List<ThavenMood> GetMoods() => ReadMoods(MoodContainer);

    public List<ThavenMood> GetSharedMoods() => ReadMoods(SharedMoodContainer);

    private void MoveUp(List<ThavenMood> list, int index, bool shared)
    {
        if (index <= 0)
            return;

        (list[index], list[index - 1]) = (list[index - 1], list[index]);
        SetState(shared ? GetMoods() : list, shared ? list : GetSharedMoods());
    }

    private void MoveDown(List<ThavenMood> list, int index, bool shared)
    {
        if (index >= list.Count - 1)
            return;

        (list[index], list[index + 1]) = (list[index + 1], list[index]);
        SetState(shared ? GetMoods() : list, shared ? list : GetSharedMoods());
    }

    private void Delete(List<ThavenMood> list, int index, bool shared)
    {
        list.RemoveAt(index);

        SetState(shared ? GetMoods() : list, shared ? list : GetSharedMoods());
    }

    private void PopulateMoodContainer(BoxContainer container, List<ThavenMood> moods, bool shared)
    {
        container.RemoveAllChildren();
        for (var i = 0; i < moods.Count; i++)
        {
            var index = i; // Copy for the closure
            var mood = moods[i];
            var moodControl = new MoodContainer(mood, shared);
            moodControl.MoveUp.OnPressed += _ => MoveUp(moods, index, shared);
            moodControl.MoveDown.OnPressed += _ => MoveDown(moods, index, shared);
            moodControl.Delete.OnPressed += _ => Delete(moods, index, shared);
            container.AddChild(moodControl);
        }
    }

    public void SetState(List<ThavenMood> moods, List<ThavenMood> sharedMoods)
    {
        _moods = moods;
        _sharedMoods = sharedMoods;

        PopulateMoodContainer(MoodContainer, _moods, false);
        PopulateMoodContainer(SharedMoodContainer, _sharedMoods, true);
    }
}

