using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface;
using Content.Shared.Research;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Serialization;

using Content.Omu.Shared._BSD.SignalSCI.SharedDishConsole;

namespace Content.Omu.Client._BSD.SignalSCI.UI;

[GenerateTypedNameReferences]
public sealed partial class DishControllMenu : FancyWindow
{
    public event Action<float>? onAngleChange;
    public event Action? OnServerButtonPressed;
    public event Action? OnPrintButtonPressed;

    public DishControllMenu()
    {
        RobustXamlLoader.Load(this);
        AngleRequest.IsValid += IsValid;
        AngleRequest.ValueChanged += (args) =>
        {
            onAngleChange?.Invoke(args.Value);
        };
        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PrintButton.OnPressed += _ => OnPrintButtonPressed?.Invoke();
    }

    public void Update(DishConsoleBoundUserInterfaceState state)
    {
        if (!AngleRequest.LineEditControl.HasKeyboardFocus())
            AngleRequest.Value = (int)state.RequestedAngle;
    }
    private bool IsValid(int arg)
    {
        if (arg < 0.0f)
            return false;

        if (arg > 360.0f)
            return false;
        return true;
    }
}