using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface;
using Content.Shared.Research;

using Content.Client.Computer;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Serialization;

using Content.Omu.Shared._BSD.SignalSCI.SharedDishConsole;

namespace Content.Omu.Client._BSD.SingalSci.UI;

[GenerateTypedNameReferences]
public sealed partial class DishControllMenue : FancyWindow
{
    public DishControllMenue()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        PanelRotation.OnTextEntered += text =>
            {
                if (!float.TryParse((string?) text.Text, out var value))
                    return;

                DishConsoleSetRequestedAngleMessage msg = new(value);

                cb.SendMessage(msg);
            };
    }


}
