using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface;
using Content.Shared.Research;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Serialization;

using Content.Omu.Shared._BSD.SignalSCI.SharedDishConsole;

namespace Content.Omu.Client._BSD.SignalSCI.UI;

[GenerateTypedNameReferences]
public sealed partial class DishControllMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnPrintButtonPressed;

    public DishControllMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PrintButton.OnPressed += _ => OnPrintButtonPressed?.Invoke();
    }

    public void Update(DishConsoleBoundUserInterfaceState state)
    {
        PrintButton.Disabled = !state.CanPrint;
    }
}