// SPDX-FileCopyrightText: 2019 Pieter-Jan Briers <pieterjan.briers@gmail.com>
// SPDX-FileCopyrightText: 2019 ZelteHonor <gabrieldionbouchard@gmail.com>
// SPDX-FileCopyrightText: 2020 Víctor Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Galactic Chimp <63882831+GalacticChimp@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Chris <HoofedEar@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Pancake <Pangogie@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client._BSD.ServerClientLink.UI;

    [GenerateTypedNameReferences]
    public sealed partial class ServerClientLinkMenu : DefaultWindow
    {
        private int _unlinkedServerCount;
        private int _linkedServerCount;
        private string[] _unlinkedServerNames = Array.Empty<string>();
        private string[] _linkedServerNames = Array.Empty<string>();
        private int[] _unlinkedServerIds = Array.Empty<int>();
        private int[] _linkedServerIds = Array.Empty<int>();

        public event Action<int>? OnServerSelected;
        public event Action<int>? OnServerDeselected;

        public SignalServerSelectionMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Unselected.OnItemSelected += OnItemSelectedLinking;
            Selected.OnItemSelected += OnItemSelectedUnlinking;
        }

        public void OnItemSelectedLinking(ItemList.ItemListSelectedEventArgs itemListSelectedEventArgs)
        {
            OnServerSelected?.Invoke(_unlinkedServerCount[itemListSelectedEventArgs.ItemIndex]);
        }

        public void OnItemSelectedUnlinking(ItemList.ItemListDeselectedEventArgs itemListDeselectedEventArgs)
        {
            OnServerDeselected?.Invoke(_linkedServerCount[itemListSelectedEventArgs.ItemIndex]);
        }

        public void PopulateUnselected(int serverCount, string[] serverNames, int[] serverIds, int selectedServerId)
        {
            _serverCount = serverCount;
            _serverNames = serverNames;
            _serverIds = serverIds;
            _selectedServerId = selectedServerId;

            // Disable so we can select the new selected server without triggering a new sync request.
            Unselected.OnItemSelected -= OnItemSelected;
            Unselected.OnItemDeselected -= OnItemDeselected;

            Unselected.Clear();
            for (var i = 0; i < _serverCount; i++)
            {
                var id = _serverIds[i];
                Unselected.AddItem(Loc.GetString("research-client-server-selection-menu-server-entry-text", ("id", id), ("serverName", _serverNames[i])));
                if (id == _selectedServerId)
                {
                    Unselected[i].Selected = true;
                }
            }

            Unselected.OnItemSelected += OnItemSelected;
            Unselected.OnItemDeselected += OnItemDeselected;
        }
    }
