using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface;
using Content.Shared.Research;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Serialization;

namespace Content.Omu.Client._BSD.ServerClientLink.UI;

[GenerateTypedNameReferences]
public sealed partial class ServerClientLinkMenu : FancyWindow
{
    private int _unlinkedServerCount;
    private int _linkedServerCount;
    private string[] _unlinkedServerNames = Array.Empty<string>();
    private string[] _linkedServerNames = Array.Empty<string>();
    private int[] _unlinkedServerIds = Array.Empty<int>();
    private int[] _linkedServerIds = Array.Empty<int>();
    public event Action<int>? OnServerSelected;
    public event Action<int>? OnServerDeselected;

    public ServerClientLinkMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Unselected.OnItemSelected += OnItemSelectedLinking;
        Selected.OnItemSelected += OnItemSelectedUnlinking;
    }

    public void OnItemSelectedLinking(ItemList.ItemListSelectedEventArgs itemListSelectedEventArgs)
    {
        OnServerSelected?.Invoke(itemListSelectedEventArgs.ItemIndex);
    }

    public void OnItemSelectedUnlinking(ItemList.ItemListSelectedEventArgs itemListSelectedEventArgs)
    {
        OnServerDeselected?.Invoke(itemListSelectedEventArgs.ItemIndex);
    }

    public void PopulateUnselected(int serverCount, string[] serverNames, int[] serverIds, int selectedServerId)
    {
        
    }
}
