using Content.Client.UserInterface.Controls;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Serialization;




namespace Content.Omu.Client._BSD.IngameConsoleUI.UI;

[GenerateTypedNameReferences]
public sealed partial class IngameConsoleMenue : FancyWindow
{
    public event Action<string>? CommandAttempt;
    public IngameConsoleMenue()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Input.OnTextEntered += AttemptedCommandFunction;
    }

    public void AttemptedCommandFunction(LineEdit.LineEditEventArgs text)
    {
        CommandAttempt?.Invoke(text.Text);
    }

    public void PopulateHistory(string[] history)
    {
        ConsoleOutPut.Clear();
        for (int iterator = 0; iterator < history.Length; iterator++)
        {
            ConsoleOutPut.AddItem(history[iterator]);
        }
        return;
    }

}
