using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface;
using Content.Shared.Research;

using Content.Client.Computer;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Serialization;



namespace Content.Omu.Client._BSD.IngameConsoleUI.UI;

[GenerateTypedNameReferences]
public sealed partial class IngameConsoleMenue : FancyWindow
{
    public IngameConsoleMenue()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Input.OnTextEntered += AngleEnter;
    }

    public void AngleEnter(LineEdit.LineEditEventArgs text)
    {
        if (!float.TryParse((string?) text.Text, out var value))
            return;

        //DishConsoleSetRequestedAngleMessage msg = new(value);

        //SendMessage(msg);
    }


}
